"""
game_objects.py

Defines the core data structures for the simulation using dataclasses.
These objects represent the physical and economic components of the game world.
"""

from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional, Any

# --- World and Network Objects ---

@dataclass
class Node:
    """Represents a single point on the map, which can be an industry or a city."""
    id: int
    name: str
    pos: Tuple[int, int]
    node_type: str  # 'city' or 'industry'
    industry_type: Optional[str] = None # e.g., 'coal_mine', 'steel_mill'
    industry_category: Optional[str] = None # e.g., 'forest', 'manufacturing'

    # --- New Industry Properties ---
    # Defines the potential production/consumption rate in cars per month.
    base_capacity: int = 0
    # List of day numbers (0=Mon, 6=Sun) this industry is open.
    business_days: List[int] = field(default_factory=list)
    # A 0-100 rating of player service. Affects industry growth.
    service_rating: float = 50.0
    # A list of active contracts associated with this node.
    active_contracts: List['Contract'] = field(default_factory=list)
    # Railcars currently located at this node's yard.
    cars_at_node: List['Railcar'] = field(default_factory=list)

@dataclass
class Link:
    """Represents a track connection between two nodes."""
    node1_id: int
    node2_id: int
    length: float
    terrain: str

# --- Economic and Cargo Objects ---

@dataclass
class Railcar:
    """Represents a single railcar."""
    id: int
    railcar_type: str # e.g., 'boxcar', 'flatcar'. Key into config.RAILCARS
    current_location_id: Optional[int] # Node ID
    state: str = "empty"  # See Waybill lifecycle for states
    waybill: Optional['Waybill'] = None # The specific waybill this car is servicing
    ticks_in_state: int = 0

@dataclass
class Waybill:
    """
    Represents a single, specific shipping order for one railcar,
    generated by an active Contract.
    """
    id: int
    contract_id: int
    origin_id: int
    destination_id: int
    cargo: str
    creation_tick: int
    service_due_tick: int
    delivery_due_tick: int

    # --- State Machine for the Waybill Lifecycle ---
    # Pending -> Servicing -> Loading -> WaitingForPickup -> InTransit -> Unloading -> Completed
    state: str = "Pending"

    assigned_train_id: Optional[int] = None
    assigned_railcar_id: Optional[int] = None


@dataclass
class Contract:
    """
    Represents a long-term shipping agreement between two industries,
    based on the new economic model.
    """
    id: int
    origin_id: int
    destination_id: int
    cargo: str

    # --- Contract Terms ---
    cars_per_month: int
    revenue_per_car: int # Base revenue, distance bonus applied at delivery

    # --- Deadlines & Duration ---
    # The time limits for each Waybill generated by this contract.
    deadline_empty_car_hours: int
    deadline_loaded_car_hours: int
    # The tick when this contract offer expires if not accepted.
    acceptance_deadline_tick: int
    # The tick when this active contract expires.
    expiration_tick: int

    # --- State Machine ---
    # offered -> active -> expired | cancelled
    status: str = "offered"

# --- Player-Managed Objects ---

@dataclass
class Train:
    """Represents a player-defined train with a locomotive and a schedule."""
    id: int
    name: str
    locomotive_type: str
    schedule: List[int] # List of Node IDs to visit in order
    current_location_id: Optional[int] # Node ID where the head of the train is
    cars: List[Railcar] = field(default_factory=list)
    state: str = "idle" # 'idle', 'running', 'switching', 'waiting_for_yard_space'

    # The train's current task, e.g., servicing a specific waybill
    current_task: Optional[Any] = None

    # For realistic movement
    path: List[int] = field(default_factory=list)
    path_index: int = 0
    progress_on_link: float = 0.0
    current_link: Optional[Tuple[int, int]] = None
